# version: "3.8"

services:

  backend:
    build: ./server
    container_name: backend
    env_file:
      - ./server/.env
    expose:
      - "3000"
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: barterbrain-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      backend :
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data: