# Use lightweight Node image
FROM node:18-alpine

# Set working directory
WORKDIR /server

# Copy package files first (better caching)
COPY package*.json ./

# Install dependencies
# RUN npm install
RUN npm ci 
# ci because it gives Jenkins/Docker reproducible dependency installation based on your lockfile.

# Copy rest of the code
COPY . .

# Expose backend port
EXPOSE 3000

#RUN npm install -g nodemon

# Start server
CMD ["node", "server.js"]

# FROM node:22-alpine AS dependencies

# WORKDIR /server

# COPY package*.json ./

# RUN npm ci --omit=dev


# FROM node:22-alpine AS production

# WORKDIR /server

# ENV NODE_ENV=production

# COPY --from=dependencies /server/node_modules ./node_modules
# COPY . .

# EXPOSE 3000

# USER node

# CMD ["node", "server.js"]