apiVersion: v1
kind: Secret

metadata:
  name: backend-secrets

type: Opaque

data:
  DATABASE_URL: "postgresql://neondb_owner:npg_eg-pooler.aws.neon.tech&channel_binding=require"
  JWT_SECRET: bf4u5=