# Use lightweight Node image
FROM node:18-alpine

# Set working directory
WORKDIR /server

# Copy package files first (better caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the code
COPY . .

# Expose backend port
EXPOSE 3000

RUN npm install -g nodemon

# Start server
CMD ["nodemon", "server.js"]