apiVersion: v1
kind: Secret

metadata:
  name: backend-secrets

type: Opaque

data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL23QtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmU="
  JWT_SECRET: "YmZqa2Ro1NQ=="