apiVersion: v1
kind: Secret

metadata:
  name: backend-secrets
  namespace: development
type: Opaque

data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfMHlVeFZsN1RRdkN1QGVwLWNvb2wtc25vdy1hbjg0ZjZlZy1wb29sZXIuYy02LnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmU="
  JWT_SECRET: "YmZqa2Roc2ZrZ3NrZmZqZGhnOTgzNHk1dTh5MjN1NHk1dTIzeTR1NQ=="
  JWT_SECRET_KEY: "YmZqa2Roc2ZrZ3NrZmZqZGhnOTgzNHk1dTh5MjN1NHk1dTIzeTR1NQ=="