apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: development
spec:
  selector:
    app: server
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
